name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"   # run a few times per day
  workflow_dispatch:          # allow manual runs from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write         # important so it can push to the output branch

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ManzarMaaz
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Push snake to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
